
services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong_Password123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong_Password123", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build:
      context: .                               
      dockerfile: Api/Dockerfile              
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=sql,1433;Database=ApiDb;User Id=sa;Password=YourStrong_Password123;TrustServerCertificate=True
    depends_on:
      sql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sql_data:
    name: sql_data
